
logging:
    level:
        com.oneyear: TRACE
        
mybatis: 
   mapperLocations: classpath*:com.oneyear.spider.mapper\*.xml
spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://118.31.12.253:3306/myBlog?characterEncoding=utf8&useSSL=true
        username: root
        password: Iamcoder@2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
         cache: false